apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini-rca
  namespace: kagent
spec:
  provider: Gemini
  model: gemini-2.5-flash
  apiKeySecret: kagent-gemini
  apiKeySecretKey: GOOGLE_API_KEY
